### ISSUE TITLE
Error processing LoginPacket: Required property "XUID"

### ISSUE THREAD

**Issue by LordBombardir** [mhsjlw/pocket-minecraft-protocol#168] opened 2021-12-31 07:57 UTC
Hello. When trying to connect to the server via client.js the following error occurs: Bad packet (error ID 3fdc2892da79): Error processing LoginPacket: Required property "XUID" of class pocketmine\network\mcpe\protocol\types\login\AuthenticationData is missing in JSON data. How can this be solved?

**Comment by extremeheat** [comment] 2021-12-31 08:52
Set `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, rerun and post the log

Most likely you are not being authenticated properly

**Comment by LordBombardir** [comment] 2021-12-31 12:42
> 

Thank you, I will definitely try

**Comment by LordBombardir** [comment] 2021-12-31 13:02
> Set `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, rerun and post the log
> 
> Most likely you are not being authenticated properly

Unfortunately, everything is also:(

**Comment by LordBombardir** [comment] 2021-12-31 13:09
Made "offline: false". Now the error comes out: "Bad packet (error ID 888d298ac4e3): Error processing LoginPacket: JsonProperty "XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\clientData"

**Comment by extremeheat** [comment] 2021-12-31 15:26
Cannot reproduce this issue. A separate issue with skins is fixed in #169 , if you continue to have this issue you need to provide the debug log

**Comment by extremeheat** [comment] 2022-02-03 00:07
Closing, if you still have the problem please re open with more information

**Closed as completed by extremeheat** 2022-02-03 00:07 UTC
